package com.sony.imaging.app.srctrl.webapi.definition;

import java.util.Arrays;
import java.util.Comparator;

/* loaded from: classes.dex */
public class Name {
    public static final String DELETE_CONTENT = "deleteContent";
    public static final String GET_CONTENT_COUNT = "getContentCount";
    public static final String GET_CONTENT_LIST = "getContentList";
    public static final String GET_SCHEME_LIST = "getSchemeList";
    public static final String GET_SOURCE_LIST = "getSourceList";
    private static final String PARAM_EXPOSURE_COMPENSATION = "ExposureCompensation";
    private static final String PARAM_LIVEVIEW = "Liveview";
    private static final String PARAM_REC_MODE = "RecMode";
    private static final String PARAM_SELF_TIMER = "SelfTimer";
    private static final String PARAM_TAKE_PICTURE = "TakePicture";
    public static final String PAUSE_STREAMING = "pauseStreaming";
    public static final String PREFIX_ACT = "act";
    public static final String PREFIX_AWAIT = "await";
    public static final String PREFIX_GET = "get";
    public static final String PREFIX_GET_AVAILABLE = "getAvailable";
    public static final String PREFIX_GET_SUPPORTED = "getSupported";
    public static final String PREFIX_SET = "set";
    public static final String PREFIX_START = "start";
    public static final String PREFIX_STOP = "stop";
    public static final String REQUEST_TO_NOTIFY_STREAMING_STATUS = "requestToNotifyStreamingStatus";
    public static final String SEEK_STREAMING_POSITION = "seekStreamingPosition";
    public static final String SET_FOCUS_MODE = "setFocusMode";
    public static final String SET_STREAMING_CONTENT = "setStreamingContent";
    public static final String START_STREAMING = "startStreaming";
    public static final String STOP_MOVIE_REC = "stopMovieRec";
    public static final String STOP_STREAMING = "stopStreaming";
    public static final String[] s_AV_CONTENT_LIST;
    public static final String[] s_PREINSTALL_API_LIST;
    public static final Comparator<String> s_COMP = new Comparator<String>() { // from class: com.sony.imaging.app.srctrl.webapi.definition.Name.1
        @Override // java.util.Comparator
        public int compare(String l, String r) {
            return l.compareTo(r);
        }
    };
    public static final String GET_VERSIONS = "getVersions";
    public static final String GET_METHOD_TYPES = "getMethodTypes";
    public static final String GET_APPLICATION_INFO = "getApplicationInfo";
    public static final String ACT_TAKE_PICTURE = "actTakePicture";
    public static final String AWAIT_TAKE_PICTURE = "awaitTakePicture";
    public static final String SET_EXPOSURE_COMPENSATION = "setExposureCompensation";
    public static final String GET_EXPOSURE_COMPENSATION = "getExposureCompensation";
    public static final String GET_AVAILABLE_EXPOSURE_COMPENSATION = "getAvailableExposureCompensation";
    public static final String GET_SUPPORTED_EXPOSURE_COMPENSATION = "getSupportedExposureCompensation";
    public static final String START_LIVEVIEW = "startLiveview";
    public static final String STOP_LIVEVIEW = "stopLiveview";
    public static final String GET_LIVEVIEW_SIZE = "getLiveviewSize";
    public static final String GET_AVAILABLE_LIVEVIEW_SIZE = "getAvailableLiveviewSize";
    public static final String GET_SUPPORTED_LIVEVIEW_SIZE = "getSupportedLiveviewSize";
    public static final String START_LIVEVIEW_WITH_SIZE = "startLiveviewWithSize";
    public static final String SET_LIVEVIEW_FRAME_INFO = "setLiveviewFrameInfo";
    public static final String GET_LIVEVIEW_FRAME_INFO = "getLiveviewFrameInfo";
    public static final String START_REC_MODE = "startRecMode";
    public static final String STOP_REC_MODE = "stopRecMode";
    public static final String SET_SELF_TIMER = "setSelfTimer";
    public static final String GET_SELF_TIMER = "getSelfTimer";
    public static final String GET_AVAILABLE_SELF_TIMER = "getAvailableSelfTimer";
    public static final String GET_SUPPORTED_SELF_TIMER = "getSupportedSelfTimer";
    public static final String GET_AVAILABLE_API_LIST = "getAvailableApiList";
    public static final String SET_WHITEBALANCE = "setWhiteBalance";
    public static final String GET_WHITEBALANCE = "getWhiteBalance";
    public static final String GET_AVAILABLE_WHITEBALANCE = "getAvailableWhiteBalance";
    public static final String GET_SUPPORTED_WHITEBALANCE = "getSupportedWhiteBalance";
    public static final String GET_EVENT = "getEvent";
    public static final String SET_TOUCHAFPOSITION = "setTouchAFPosition";
    public static final String GET_TOUCHAFPOSITION = "getTouchAFPosition";
    public static final String CANCEL_TOUCHAFPOSITION = "cancelTouchAFPosition";
    public static final String SET_FNUMBER = "setFNumber";
    public static final String GET_FNUMBER = "getFNumber";
    public static final String GET_AVAILABLE_FNUMBER = "getAvailableFNumber";
    public static final String GET_SUPPORTED_FNUMBER = "getSupportedFNumber";
    public static final String SET_SHUTTERSPEED = "setShutterSpeed";
    public static final String GET_SHUTTERSPEED = "getShutterSpeed";
    public static final String GET_AVAILABLE_SHUTTERSPEED = "getAvailableShutterSpeed";
    public static final String GET_SUPPORTED_SHUTTERSPEED = "getSupportedShutterSpeed";
    public static final String SET_ISOSPEEDRATE = "setIsoSpeedRate";
    public static final String GET_ISOSPEEDRATE = "getIsoSpeedRate";
    public static final String GET_AVAILABLE_ISOSPEEDRATE = "getAvailableIsoSpeedRate";
    public static final String GET_SUPPORTED_ISOSPEEDRATE = "getSupportedIsoSpeedRate";
    public static final String SET_EXPOSURE_MODE = "setExposureMode";
    public static final String GET_EXPOSURE_MODE = "getExposureMode";
    public static final String GET_AVAILABLE_EXPOSURE_MODE = "getAvailableExposureMode";
    public static final String GET_SUPPORTED_EXPOSURE_MODE = "getSupportedExposureMode";
    public static final String GET_STORAGE_INFORMATION = "getStorageInformation";
    public static final String SET_POSTVIEWIMAGE_SIZE = "setPostviewImageSize";
    public static final String GET_POSTVIEWIMAGE_SIZE = "getPostviewImageSize";
    public static final String GET_AVAILABLE_POSTVIEWIMAGE_SIZE = "getAvailablePostviewImageSize";
    public static final String GET_SUPPORTED_POSTVIEWIMAGE_SIZE = "getSupportedPostviewImageSize";
    public static final String SET_PROGRAMSHIFT = "setProgramShift";
    public static final String GET_SUPPORTED_PROGRAMSHIFT = "getSupportedProgramShift";
    public static final String SET_SHOOTMODE = "setShootMode";
    public static final String GET_SHOOTMODE = "getShootMode";
    public static final String GET_AVAILABLE_SHOOTMODE = "getAvailableShootMode";
    public static final String GET_SUPPORTED_SHOOTMODE = "getSupportedShootMode";
    public static final String SET_FLASH_MODE = "setFlashMode";
    public static final String GET_FLASH_MODE = "getFlashMode";
    public static final String GET_AVAILABLE_FLASH_MODE = "getAvailableFlashMode";
    public static final String GET_SUPPORTED_FLASH_MODE = "getSupportedFlashMode";
    public static final String SET_CONTSHOOTING_MODE = "setContShootingMode";
    public static final String GET_CONTSHOOTING_MODE = "getContShootingMode";
    public static final String GET_AVAILABLE_CONSHOOTING_MODE = "getAvailableContShootingMode";
    public static final String GET_SUPPORTED_CONSHOOTING_MODE = "getSupportedContShootingMode";
    public static final String SET_CONTSHOOTING_SPEED = "setContShootingSpeed";
    public static final String GET_CONTSHOOTING_SPEED = "getContShootingSpeed";
    public static final String GET_AVAILABLE_CONSHOOTING_SPEED = "getAvailableContShootingSpeed";
    public static final String GET_SUPPORTED_CONSHOOTING_SPEED = "getSupportedContShootingSpeed";
    public static final String ACT_ZOOM = "actZoom";
    public static final String START_CONTSHOOTING = "startContShooting";
    public static final String STOP_CONTSHOOTING = "stopContShooting";
    public static final String START_BULB_SHOOTING = "startBulbShooting";
    public static final String STOP_BULB_SHOOTING = "stopBulbShooting";
    public static final String START_MOVIE_REC = "startMovieRec";
    public static final String GET_FOCUS_MODE = "getFocusMode";
    public static final String GET_AVAILABLE_FOCUS_MODE = "getAvailableFocusMode";
    public static final String GET_SUPPORTED_FOCUS_MODE = "getSupportedFocusMode";
    public static final String SET_ZOOM_SETTING = "setZoomSetting";
    public static final String GET_ZOOM_SETTING = "getZoomSetting";
    public static final String GET_AVAILABLE_ZOOM_SETTING = "getAvailableZoomSetting";
    public static final String GET_SUPPORTED_ZOOM_SETTING = "getSupportedZoomSetting";
    public static final String SET_CAMERA_FUNCTION = "setCameraFunction";
    public static final String GET_CAMERA_FUNCTION = "getCameraFunction";
    public static final String GET_AVAILABLE_CAMERA_FUNCTION = "getAvailableCameraFunction";
    public static final String GET_SUPPORTED_CAMERA_FUNCTION = "getSupportedCameraFunction";
    public static final String ACT_HALFPRESSSHUTTER = "actHalfPressShutter";
    public static final String CANCEL_HALFPRESSSHUTTER = "cancelHalfPressShutter";
    public static final String SET_SILENT_SHOOTING = "setSilentShootingSetting";
    public static final String GET_SILENT_SHOOTING = "getSilentShootingSetting";
    public static final String GET_AVAILABLE_SILENT_SHOOTING = "getAvailableSilentShootingSetting";
    public static final String GET_SUPPORTED_SILENT_SHOOTING = "getSupportedSilentShootingSetting";
    public static final String[] s_DEFAULT_API_LIST = {GET_VERSIONS, GET_METHOD_TYPES, GET_APPLICATION_INFO, ACT_TAKE_PICTURE, AWAIT_TAKE_PICTURE, SET_EXPOSURE_COMPENSATION, GET_EXPOSURE_COMPENSATION, GET_AVAILABLE_EXPOSURE_COMPENSATION, GET_SUPPORTED_EXPOSURE_COMPENSATION, START_LIVEVIEW, STOP_LIVEVIEW, GET_LIVEVIEW_SIZE, GET_AVAILABLE_LIVEVIEW_SIZE, GET_SUPPORTED_LIVEVIEW_SIZE, START_LIVEVIEW_WITH_SIZE, SET_LIVEVIEW_FRAME_INFO, GET_LIVEVIEW_FRAME_INFO, START_REC_MODE, STOP_REC_MODE, SET_SELF_TIMER, GET_SELF_TIMER, GET_AVAILABLE_SELF_TIMER, GET_SUPPORTED_SELF_TIMER, GET_AVAILABLE_API_LIST, SET_WHITEBALANCE, GET_WHITEBALANCE, GET_AVAILABLE_WHITEBALANCE, GET_SUPPORTED_WHITEBALANCE, GET_EVENT, SET_TOUCHAFPOSITION, GET_TOUCHAFPOSITION, CANCEL_TOUCHAFPOSITION, SET_FNUMBER, GET_FNUMBER, GET_AVAILABLE_FNUMBER, GET_SUPPORTED_FNUMBER, SET_SHUTTERSPEED, GET_SHUTTERSPEED, GET_AVAILABLE_SHUTTERSPEED, GET_SUPPORTED_SHUTTERSPEED, SET_ISOSPEEDRATE, GET_ISOSPEEDRATE, GET_AVAILABLE_ISOSPEEDRATE, GET_SUPPORTED_ISOSPEEDRATE, SET_EXPOSURE_MODE, GET_EXPOSURE_MODE, GET_AVAILABLE_EXPOSURE_MODE, GET_SUPPORTED_EXPOSURE_MODE, GET_STORAGE_INFORMATION, SET_POSTVIEWIMAGE_SIZE, GET_POSTVIEWIMAGE_SIZE, GET_AVAILABLE_POSTVIEWIMAGE_SIZE, GET_SUPPORTED_POSTVIEWIMAGE_SIZE, SET_PROGRAMSHIFT, GET_SUPPORTED_PROGRAMSHIFT, SET_SHOOTMODE, GET_SHOOTMODE, GET_AVAILABLE_SHOOTMODE, GET_SUPPORTED_SHOOTMODE, SET_FLASH_MODE, GET_FLASH_MODE, GET_AVAILABLE_FLASH_MODE, GET_SUPPORTED_FLASH_MODE, SET_CONTSHOOTING_MODE, GET_CONTSHOOTING_MODE, GET_AVAILABLE_CONSHOOTING_MODE, GET_SUPPORTED_CONSHOOTING_MODE, SET_CONTSHOOTING_SPEED, GET_CONTSHOOTING_SPEED, GET_AVAILABLE_CONSHOOTING_SPEED, GET_SUPPORTED_CONSHOOTING_SPEED, ACT_ZOOM, START_CONTSHOOTING, STOP_CONTSHOOTING, START_BULB_SHOOTING, STOP_BULB_SHOOTING, START_MOVIE_REC, "stopMovieRec", "setFocusMode", GET_FOCUS_MODE, GET_AVAILABLE_FOCUS_MODE, GET_SUPPORTED_FOCUS_MODE, SET_ZOOM_SETTING, GET_ZOOM_SETTING, GET_AVAILABLE_ZOOM_SETTING, GET_SUPPORTED_ZOOM_SETTING, SET_CAMERA_FUNCTION, GET_CAMERA_FUNCTION, GET_AVAILABLE_CAMERA_FUNCTION, GET_SUPPORTED_CAMERA_FUNCTION, ACT_HALFPRESSSHUTTER, CANCEL_HALFPRESSSHUTTER, SET_SILENT_SHOOTING, GET_SILENT_SHOOTING, GET_AVAILABLE_SILENT_SHOOTING, GET_SUPPORTED_SILENT_SHOOTING};

    static {
        Arrays.sort(s_DEFAULT_API_LIST);
        s_PREINSTALL_API_LIST = new String[]{GET_VERSIONS, GET_METHOD_TYPES, GET_APPLICATION_INFO, ACT_TAKE_PICTURE, AWAIT_TAKE_PICTURE, SET_EXPOSURE_COMPENSATION, GET_EXPOSURE_COMPENSATION, GET_AVAILABLE_EXPOSURE_COMPENSATION, GET_SUPPORTED_EXPOSURE_COMPENSATION, START_LIVEVIEW, STOP_LIVEVIEW, START_REC_MODE, STOP_REC_MODE, SET_SELF_TIMER, GET_SELF_TIMER, GET_AVAILABLE_SELF_TIMER, GET_SUPPORTED_SELF_TIMER, GET_AVAILABLE_API_LIST, GET_EVENT, SET_SHOOTMODE, GET_SHOOTMODE, GET_AVAILABLE_SHOOTMODE, GET_SUPPORTED_SHOOTMODE, SET_FLASH_MODE, GET_FLASH_MODE, GET_AVAILABLE_FLASH_MODE, GET_SUPPORTED_FLASH_MODE, ACT_ZOOM, START_MOVIE_REC, "stopMovieRec"};
        Arrays.sort(s_PREINSTALL_API_LIST);
        s_AV_CONTENT_LIST = new String[]{GET_VERSIONS, GET_METHOD_TYPES, GET_SCHEME_LIST, GET_SOURCE_LIST, GET_CONTENT_COUNT, GET_CONTENT_LIST, DELETE_CONTENT, SET_STREAMING_CONTENT, START_STREAMING, PAUSE_STREAMING, STOP_STREAMING, REQUEST_TO_NOTIFY_STREAMING_STATUS, SEEK_STREAMING_POSITION};
        Arrays.sort(s_AV_CONTENT_LIST);
    }
}
