package com.sony.imaging.app.startrails.util;

import android.graphics.Bitmap;
import com.sony.imaging.app.base.shooting.camera.CreativeStyleController;
import com.sony.imaging.app.base.shooting.camera.ExposureModeController;
import com.sony.imaging.app.base.shooting.camera.PictureEffectController;
import com.sony.imaging.app.startrails.AppContext;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/* loaded from: classes.dex */
public class STConstants {
    public static final int BRIGHT_NIGHT_DEFAULT_LEVEL = 4;
    public static final int BRIGHT_NIGHT_DEFAULT_REC_MODE = 0;
    public static final int BRIGHT_NIGHT_DEFAULT_SHOT = 480;
    public static final String BRIGHT_NIGHT_WB_OPTOIN_VALUE = "-4/0/0";
    public static final int CAPTURE_DELAY_TIME = 2500;
    public static final String CAPTURING_FINISH = "capturing_finish";
    public static final String CAPTURING_STARTED = "capturing_started";
    public static final String CAPTURING_TWO_SEC_FINISH = "capturing_two_sec_finish";
    public static final String CUSTOM_CREATIVE_STYLE = "standard";
    public static final int CUSTOM_DEFAULT_LEVEL = 4;
    public static final int CUSTOM_DEFAULT_REC_MODE = 0;
    public static final int CUSTOM_DEFAULT_SHOT = 480;
    public static final String CUSTOM_WB_OPTOIN_VALUE = "0/0/0";
    public static final int DARK_NIGHT_DEFAULT_LEVEL = 4;
    public static final int DARK_NIGHT_DEFAULT_SHOT = 480;
    public static final int DARK_NIGHT_FVAL_MIN_STEP = -40;
    public static final int DARK_NIGHT_NIGHT_DEFAULT_REC_MODE = 0;
    public static final String DARK_NIGHT_WB_OPTOIN_VALUE = "-2/0/0";
    public static final int DEFAULT_VALUE_BRIGHT_NIGHT_EXPOSURE_COMPENSATION = 2;
    public static final int DEFAULT_VALUE_ONE = 1;
    public static final String DEFAULT_VALUE_SHUTTER_SPEED = "5\"";
    public static final String DEFAULT_VALUE_SHUTTER_SPEED_DARK_NIGHT = "10\"";
    public static final int DEFAULT_VALUE_SHUTTER_SPEED_POSITION = 8;
    public static final int DEFAULT_VALUE_ZERO = 0;
    public static final String FORMAT_BIG_DIGIT = "F%.0f";
    public static final String FORMAT_ONE_DIGIT = "F%.1f";
    public static final int INTEGER_CONSTANT_ZERO = 0;
    public static final String INVALID_APERTURE_STRING = "F--";
    public static final float INVALID_APERTURE_VALUE = 0.0f;
    public static final int INVALID_INTEGER_CONSTANTS = -1;
    public static final int MAX_BITMAP_NUM = 5;
    public static final int MINIMUM_VALUE_SHUTTER_SPEED_POSITION_DARK_NIGHT = 15;
    public static final String MONITOR_BRIGHTNESS_OFF = "Darker";
    public static final String MONITOR_BRIGHTNESS_ON = "Normal";
    public static final String MOVIE_1280_720 = "MOVIE_1280_720";
    public static final String MOVIE_1920_1080 = "MOVIE_1920_1080";
    public static final String MS_CARD_PATH = "/MSSONY/CAM_APPS/APP_STRS";
    public static final String NONE = "none";
    public static final float NUMBER_100 = 100.0f;
    public static final int PB_DISPLAY_MODE_INFO_OFF = 0;
    public static final int PB_DISPLAY_MODE_INFO_ON = 1;
    public static final int RECORDING_MODE_24 = 0;
    public static final int RECORDING_MODE_30 = 1;
    public static final String REMOVE_CAPTURE_CALLBACK = "REMOVE_CAPTURE_CALLBACK";
    public static final String SD_CARD_PATH = "/PRIVATE/SONY/APP_STRS";
    public static final String SELF_TIMER_OFF = "selftimeroff";
    public static final String SELF_TIMER_ON = "selftimeron";
    public static final int THEME_BRIGHT_NIGHT = 0;
    public static final int THEME_CUSTOM = 2;
    public static final int THEME_DARK_NIGHT = 1;
    public static final String THEME_TAG_UPDATED = "themeupdate";
    public static final float THRESHODL_BIG_OR_ONE = 10.0f;
    public static final float THRESHODL_ONE = 1.0f;
    public static final String TIMER_UPDATE = "TIMER_UPDATE";
    public static final String TYPE_INFO_DB_PATH = "/PRIVATE/";
    public static final String TYPE_INFO_FILENAME = "TYPEINFO.XML";
    public static final String LIB_PATH = "/android/data/lib/" + AppContext.getAppContext().getPackageName() + "/lib/";
    public static int sCaptureImageCounter = 0;
    public static String THUMBNAIL_UPDATE = "THUMBNAIL_UPDATE";
    public static String PLAY_ROOT_CONTAINER_REMOVED = "PLAY_ROOT_CONTAINER_REMOVED";
    public static String UPDATE_DELETED_FRAME_AVI = "UPDATE_DELETED_FRAME_AVI";
    public static String DELETE_FRAME = "DELETE_FRAME";
    public static String UPDATE_DELETED_FRAME = "UPDATE_DELETED_FRAME";
    public static String REFRESH_PLAYBACK_VIEW = "REFRESH_PLAYBACK_VIEW";
    public static CopyOnWriteArrayList<Bitmap> sFrameBitmapList = new CopyOnWriteArrayList<>();
    public static final List<String> SELECTED_MENU_ITEM_THEME = Arrays.asList(ExposureModeController.EXPOSURE_MODE, PictureEffectController.PICTUREEFFECT, CreativeStyleController.CREATIVESTYLE);
    public static final String CUSTOM_APERTURE = "F2.8";
    public static final List<String> APERTURE_VALUE_LIST = Arrays.asList("F1.4", "F1.6", "F1.7", "F1.8", "F2.0", "F2.2", "F2.5", CUSTOM_APERTURE, "F3.2", "F3.5", "F4.0", "F4.5", "F5.0", "F5.6", "F6.3", "F7.1", "F8.0", "F9.0", "F10", "F11", "F13", "F14", "F16", "F18", "F20", "F22", "F25", "F29", "F32", "F36", "F40", "F45", "F51", "F57", "F64");
    public static String slastStateAperture = "F8.0";
    public static boolean is2SecondTimerFinish = false;
}
