package com.sony.imaging.app.doubleexposure.common;

/* loaded from: classes.dex */
public class DoubleExposureBackUpKey {
    public static String KEY_SELECTED_THEME = "KEY_SELECTED_THEME";
    public static String KEY_SELECTED_MODE = "KEY_SELECTED_MODE";
    public static String KEY_FIRST_IMAGE_ID = "KEY_FIRST_IMAGE_ID";
    public static String KEY_FIRST_IMAGE_DATA = "KEY_FIRST_IMAGE_DATA";
    public static String KEY_FIRST_IMAGE_MEDIA_ID = "KEY_FIRST_IMAGE_MEDIA_ID";
    public static String KEY_SECOND_SHOOTING_PRIORITY_VALUE = "KEY_SECOND_SHOOTING_PRIORITY_VALUE";
    public static String KEY_WEIGHTED_AVERAGE_VALUE = "KEY_WEIGHTED_AVERAGE_VALUE";
    public static String KEY_CURRENT_SHOOTING_SCREEN = "KEY_CURRENT_SHOOTING_SCREEN";
    public static String KEY_MANUAL_THEME_CAMERA_SETTINGS = "KEY_MANUAL_THEME_CAMERA_SETTINGS";
    public static String KEY_MANUAL_THEME_PICTURE_EFFECT_OPTION_VALUE = "KEY_MANUAL_THEME_PICTURE_EFFECT_OPTION_VALUE";
    public static String KEY_MANUAL_THEME_CUSTOM_WHITE_BALANCE_VALUE = "KEY_MANUAL_THEME_CUSTOM_WHITE_BALANCE_VALUE";
    public static String KEY_FIRST_SHOOTING_GUIDE_VALUES = "KEY_FIRST_SHOOTING_GUIDE_VALUES";
    public static String KEY_SECOND_SHOOTING_GUIDE_VALUES = "KEY_SECOND_SHOOTING_GUIDE_VALUES";
}
