package com.sony.imaging.app.pictureeffectplus;

/* loaded from: classes.dex */
public class PictureEffectPlusBackUpKey {
    public static final String ID_PICTUREEFFECTPLUS_CURRENT_EFFECT = "ID_PICTUREEFFECTPLUS_CURRENT_EFFECT";
    public static final String ID_PICTUREEFFECTPLUS_DRIVE_MODE_BEFORE_SAEFFECT = "ID_PICTUREEFFECTPLUS_DRIVE_MODE_BEFORE_SAEFFECT";
    public static final String ID_PICTUREEFFECTPLUS_EXPOSUREMODE_IN_DIADEM_BEFORE_CHANGE = "ID_PICTUREEFFECTPLUS_EXPOSUREMODE_IN_DIADEM_BEFORE_CHANGE";
    public static final String ID_PICTUREEFFECTPLUS_HDR_LEVEL = "ID_PICTUREEFFECTPLUS_HDR_LEVEL";
    public static final String ID_PICTUREEFFECTPLUS_ILLUST_LEVEL = "ID_PICTUREEFFECTPLUS_ILLUST_LEVEL";
    public static final String ID_PICTUREEFFECTPLUS_MINIATURE_AREA = "ID_PICTUREEFFECTPLUS_MINIATURE_AREA";
    public static final String ID_PICTUREEFFECTPLUS_MINIATURE_EFFECT = "ID_PICTUREEFFECTPLUS_MINIATURE_EFFECT";
    public static final String ID_PICTUREEFFECTPLUS_MINIATURE_EFFECT_BEFORE_AUTO = "ID_PICTUREEFFECTPLUS_MINIATURE_EFFECT_BEFORE_AUTO";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_CB = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_CB";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_COLOR = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_COLOR";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_CR = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_CR";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_PHASE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_PHASE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_RANGE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_RANGE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_SATU = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_SATU";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_Y = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH0_Y";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_CB = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_CB";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_COLOR = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_COLOR";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_CR = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_CR";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_PHASE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_PHASE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_RANGE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_RANGE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_SATU = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_SATU";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_Y = "ID_PICTUREEFFECTPLUS_PART_COLOR_CH1_Y";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_CB = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_CB";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_CR = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_CR";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_PHASE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_PHASE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_RANGE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_RANGE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_SATU = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_SATU";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_Y = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH0_Y";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_CB = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_CB";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_CR = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_CR";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_PHASE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_PHASE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_RANGE = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_RANGE";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_SATU = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_SATU";
    public static final String ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_Y = "ID_PICTUREEFFECTPLUS_PART_COLOR_CUSTOM_CH1_Y";
    public static final String ID_PICTUREEFFECTPLUS_POSTER_COLOR = "ID_PICTUREEFFECTPLUS_POSTER_COLOR";
    public static final String ID_PICTUREEFFECTPLUS_SOFT_FOCUS_LEVEL = "ID_PICTUREEFFECTPLUS_SOFT_FOCUS_LEVEL";
    public static final String ID_PICTUREEFFECTPLUS_SOFT_HIGH_KEY_COLOR = "ID_PICTUREEFFECTPLUS_SOFT_HIGH_KEY_COLOR";
    public static final String ID_PICTUREEFFECTPLUS_TOYCAMERA_COLOR = "ID_PICTUREEFFECTPLUS_TOYCAMERA_COLOR";
    public static final String ID_PICTUREEFFECTPLUS_TOYCAMERA_DARKNESS_LEVEL = "ID_PICTUREEFFECTPLUS_TOYCAMERA_DARKNESS_LEVEL";
}
