package com.sony.imaging.app.smoothreflection.common;

/* loaded from: classes.dex */
public class SmoothReflectionBackUpKey {
    public static String KEY_SELECTED_THEME = "KEY_SELECTED_THEME";
    public static String KEY_SELECTED_SMOOTH_LEVEL = "KEY_SELECTED_SMOOTH_LEVEL";
    public static String KEY_SELECTED_MONOTONE_COLOR = "KEY_SELECTED_MONOTONE_COLOR";
    public static String KEY_SELECTED_SELF_TIMER = "KEY_SELECTED_SELF_TIMER";
    public static String KEY_CUSTOM_THEME_SHOOT_MODE = "KEY_CUSTOM_THEME_SHOOT_MODE";
    public static String KEY_CUSTOM_THEME_ISO = "KEY_CUSTOM_THEME_ISO";
    public static String KEY_CUSTOM_THEME_METERING_MODE = "KEY_CUSTOM_THEME_METERING_MODE";
    public static String KEY_CUSTOM_THEME_WHITE_BALANCE = "KEY_CUSTOM_THEME_WHITE_BALANCE";
    public static String KEY_CUSTOM_THEME_WHITE_BALANCE_DETAIL = "KEY_CUSTOM_THEME_WHITE_BALANCE_DETAIL";
    public static String KEY_CUSTOM_THEME_DRO = "KEY_CUSTOM_THEME_DRO";
    public static String KEY_CUSTOM_THEME_DRO_OPTION = "KEY_CUSTOM_THEME_DRO_OPTION";
    public static String KEY_CUSTOM_THEME_CREATIVE_STYLE = "KEY_CUSTOM_THEME_CREATIVE_STYLE";
    public static String KEY_CUSTOM_THEME_CREATIVE_STYLE_DETAIL = "KEY_CUSTOM_THEME_CREATIVE_STYLE_DETAIL";
    public static String KEY_CUSTOM_THEME_PICTURE_EFFECT = "KEY_CUSTOM_THEME_PICTURE_EFFECT";
    public static String KEY_CUSTOM_THEME_PICTURE_EFFECT_OPTION = "KEY_CUSTOM_THEME_PICTURE_EFFECT_OPTION";
    public static String KEY_CUSTOM_THEME_APERTURE = "KEY_CUSTOM_THEME_APERTURE";
    public static String KEY_SELECTED_SHOTS = "KEY_SELECTED_SHOTS";
    public static String KEY_PICTUREQUALITY = "KEY_PICTUREQUALITY";
}
