package com.sony.imaging.app.portraitbeauty.common;

/* loaded from: classes.dex */
public class PortraitBeautyBackUpKey {
    public static String KEY_INTIAL_STARTUP = "false";
    public static String KEY_LEVEL_OF_WHITE_SKIN = "KEY_LEVEL_OF_WHITE_SKIN";
    public static String KEY_SELECTED_EFFECT = "KEY_SELECTED_EFFECT";
    public static String KEY_LEVEL_OF_DEFOCUS = "KEY_LEVEL_OF_DEFOCUS";
    public static String KEY_LEVEL_OF_SOFT_SKIN = "KEY_LEVEL_OF_SOFT_SKIN";
    public static String KEY_SELECTED_SELF_TIMER = "KEY_SELECTED_SELF_TIMER";
    public static String KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING = "KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING";
    public static String KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING_EVF = "KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING_EVF";
    public static String KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING_HDMI = "KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING_HDMI";
    public static String KEY_CURRENT_APERTURE_VALUE = "KEY_CURRENT_APERTURE_VALUE";
    public static String KEY_CURRENT_GAUGE_PROGRESS = "KEY_CURRENT_GAUGE_PROGRESS";
    public static String KEY_CURRENT_PATTERN = "KEY_CURRENT_PATTERN";
    public static String KEY_CURRENT_SIZE = "KEY_CURRENT_SIZE";
    public static String KEY_CURRENT_SIZE_SECONDARY = "KEY_CURRENT_SIZE_SECONDARY";
    public static String KEY_CURRENT_BRIGHTNESS = "KEY_CURRENT_BRIGHTNESS";
    public static String KEY_DEFAULT_BRIGHTNESS = "KEY_DEFAULT_BRIGHTNESS";
    public static String KEY_SELECTED_ITEM = "KEY_SELECTED_ITEM";
    public static String KEY_DEFOCUS_BACKGROUND = "KEY_DEFOCUS_BACKGROUND";
    public static String KEY_MODE_DRO = "KEY_MODE_DRO";
    public static String KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING_TIMER = "KEY_KEY_SELECTED_DISPLAY_MODE_NORMAL_SHOOTING_TIMER";
    public static String KEY_CATCHLIGHT_BRIGHTNESS = "KEY_CATCHLIGHT_BRIGHTNESS";
}
