package com.sony.imaging.app.portraitbeauty.common;

import com.sony.imaging.app.base.shooting.camera.FlashController;
import com.sony.imaging.app.base.shooting.camera.PictureEffectController;
import java.util.Arrays;
import java.util.List;

/* loaded from: classes.dex */
public class PortraitBeautyConstants {
    public static final String CANCELSHOOTINGTIMERTAG = "selftimercancel";
    public static final String DEFOCUS_EFFECT = "DEFOCUS";
    public static final int EIGHT_SECOND_MILLIS = 8000;
    public static final int ELEVEN_SECOND_MILLIS = 11000;
    public static final String FINISHTAG = "finish";
    public static final int FIVE_SECOND_MILLIS = 5000;
    public static final String FLG_ALWAYS__S_SIZE = "FLG_ALWAYS__S_SIZE";
    public static final String FLG_USE_ORIGINAL_IMAGE = "FLG_USE_ORIGINAL_IMAGE";
    public static final String FORMAT_BIG_DIGIT = "F%.0f";
    public static final String FORMAT_ONE_DIGIT = "F%.1f";
    public static final int FOUR_SECOND_MILLIS = 4000;
    public static final int IMAGE_QUALITY_EXTRAFINE = 3;
    public static final int IMAGE_QUALITY_FINE = 2;
    public static final int IMAGE_QUALITY_STANDARD = 1;
    public static final String INVALID_APERTURE_STRING = "F--";
    public static final float INVALID_APERTURE_VALUE = 0.0f;
    public static final int MSG_ID_TO_OPEN_BROWSER_STATE = 1010;
    public static final int NINE_SECOND_MILLIS = 9000;
    public static final float NUMBER_100 = 100.0f;
    public static final int ONE_SECOND_MILLIS = 1000;
    public static final int PATTERN_1 = 0;
    public static final int PATTERN_2 = 1;
    public static final int PATTERN_3 = 2;
    public static final int PATTERN_4 = 3;
    public static final int PATTERN_5 = 4;
    public static final int PATTERN_6 = 5;
    public static final int PATTERN_7 = 6;
    public static final String PROCESSING_PROGRESS_LAYOUT = "PROCESSING_PROGRESS_LAYOUT";
    public static final String PROCESSING_PROGRESS_START = "PB_PROCESSING_PROGRESS_START";
    public static final String PROCESSING_PROGRESS_STOP = "PB_PROCESSING_PROGRESS_STOP";
    public static final String SELFTIMERICONSETTINGTAG = "selftimer";
    public static final String SELFTIMERSETTINGFINISHTAG = "selftimerfinish";
    public static final String SELFTIMERUPDATEICONSETTINGTAG = "updateicon";
    public static final int SELF_TIMER_TYPE_VALUE_10_SEC = 10;
    public static final int SELF_TIMER_TYPE_VALUE_2_SEC = 2;
    public static final int SELF_TIMER_TYPE_VALUE_5_SEC = 5;
    public static final int SEVEN_SECOND_MILLIS = 7000;
    public static final int SIX_SECOND_MILLIS = 6000;
    public static final String SOFT_SKIN_EFFECT = "SOFTSKIN";
    public static final int TEN_SECOND_MILLIS = 10000;
    public static final int THREE_SECOND_MILLIS = 3000;
    public static final float THRESHODL_BIG_OR_ONE = 10.0f;
    public static final int TWO_SECOND_MILLIS = 2000;
    public static final String WHITE_SKIN_EFFECT = "WHITESKIN";
    public static final int WHITE_SKIN_LEVEL_1 = 1;
    public static final int WHITE_SKIN_LEVEL_2 = 2;
    public static final int WHITE_SKIN_LEVEL_3 = 3;
    public static final int WHITE_SKIN_LEVEL_4 = 4;
    public static final int WHITE_SKIN_LEVEL_5 = 5;
    public static final int WHITE_SKIN_LEVEL_6 = 6;
    public static final int WHITE_SKIN_LEVEL_7 = 7;
    public static boolean Resize_Key_Up = false;
    public static boolean CENTER_KEY_LR_UD = false;
    public static int mDefaultBrightness = 192;
    public static String LEFT_ON_CENTER = PictureEffectController.MINIATURE_LEFT;
    public static String RIGHT_ON_CENTER = PictureEffectController.MINIATURE_RIGHT;
    public static String UP_ON_CENTER = "up";
    public static String DOWN_ON_CENTER = "down";
    public static String FOCUS_ARROW_VISIBLE = "visible";
    public static String FOCUS_ARROW_INVISIBLE = FlashController.INVISIBLE;
    public static boolean ZOOM_MODE_LAYOUT_VISIBILITY = false;
    public static boolean isNoFaceCautionVisible = false;
    public static boolean FACE_MORE_THAN_ONE = false;
    public static boolean Brightness_Key_Up = false;
    public static int slastStateExposureCompansasion = 0;
    public static boolean sISEVDIALTURN = false;
    public static final List<String> APERTURE_VALUE_LIST = Arrays.asList("F1.0", "F1.3", "F1.4", "F1.6", "F1.7", "F1.8", "F2.0", "F2.2", "F2.5", "F2.8", "F3.2", "F3.5", "F4.0", "F4.5", "F5.0", "F5.6", "F6.3", "F7.1", "F8.0", "F9.0", "F10", "F11", "F13", "F14", "F16", "F18", "F20", "F22", "F25", "F29", "F32", "F36", "F40", "F45", "F51", "F57", "F64", "F72", "F81", "F90");
}
