package com.sony.imaging.app.srctrl.webapi.servlet;

import com.sony.imaging.app.srctrl.util.SRCtrlConstants;
import java.util.HashMap;

/* loaded from: classes.dex */
public final class MimeType {
    public static final String APPLICATION_ANDREW_INSET = "application/andrew-inset";
    public static final String APPLICATION_JAVA_ARCHIVE = "application/java-archive";
    public static final String APPLICATION_JNLP = "application/jnlp";
    public static final String APPLICATION_JSON = "application/json";
    public static final String APPLICATION_MAC_BINHEX40 = "application/mac-binhex40";
    public static final String APPLICATION_MAC_COMPACTPRO = "application/mac-compactpro";
    public static final String APPLICATION_MATHML_XML = "application/mathml+xml";
    public static final String APPLICATION_MSWORD = "application/msword";
    public static final String APPLICATION_OCTET_STREAM = "application/octet-stream";
    public static final String APPLICATION_ODA = "application/oda";
    public static final String APPLICATION_PDF = "application/pdf";
    public static final String APPLICATION_POSTSCRIPT = "application/postscript";
    public static final String APPLICATION_RDF_SMIL = "application/smil";
    public static final String APPLICATION_RDF_XML = "application/rdf+xml";
    public static final String APPLICATION_SRGS = "application/srgs";
    public static final String APPLICATION_SRGS_XML = "application/srgs+xml";
    public static final String APPLICATION_TGZ = "application/tgz";
    public static final String APPLICATION_VND_MIF = "application/vnd.mif";
    public static final String APPLICATION_VND_MOZZILLA_XUL_XML = "application/vnd.mozilla.xul+xml";
    public static final String APPLICATION_VND_MSEXCEL = "application/vnd.ms-excel";
    public static final String APPLICATION_VND_MSPOWERPOINT = "application/vnd.ms-powerpoint";
    public static final String APPLICATION_VND_RNREALMEDIA = "application/vnd.rn-realmedia";
    public static final String APPLICATION_XHTML_XML = "application/xhtml+xml";
    public static final String APPLICATION_XML = "application/xml";
    public static final String APPLICATION_XML_DTD = "application/xml-dtd";
    public static final String APPLICATION_XSLT_XML = "application/xslt+xml";
    public static final String APPLICATION_X_BCPIO = "application/x-bcpio";
    public static final String APPLICATION_X_CDLINK = "application/x-cdlink";
    public static final String APPLICATION_X_CHESS_PGN = "application/x-chess-pgn";
    public static final String APPLICATION_X_CPIO = "application/x-cpio";
    public static final String APPLICATION_X_CSH = "application/x-csh";
    public static final String APPLICATION_X_DIRECTOR = "application/x-director";
    public static final String APPLICATION_X_DVI = "application/x-dvi";
    public static final String APPLICATION_X_FUTURESPLASH = "application/x-futuresplash";
    public static final String APPLICATION_X_GTAR = "application/x-gtar";
    public static final String APPLICATION_X_GZIP = "application/x-gzip";
    public static final String APPLICATION_X_HDF = "application/x-hdf";
    public static final String APPLICATION_X_JAVASCRIPT = "application/x-javascript";
    public static final String APPLICATION_X_KOAN = "application/x-koan";
    public static final String APPLICATION_X_LATEX = "application/x-latex";
    public static final String APPLICATION_X_NETCDF = "application/x-netcdf";
    public static final String APPLICATION_X_OGG = "application/x-ogg";
    public static final String APPLICATION_X_RAR_COMPRESSED = "application/x-rar-compressed";
    public static final String APPLICATION_X_SH = "application/x-sh";
    public static final String APPLICATION_X_SHAR = "application/x-shar";
    public static final String APPLICATION_X_SHOCKWAVE_FLASH = "application/x-shockwave-flash";
    public static final String APPLICATION_X_STUFFIT = "application/x-stuffit";
    public static final String APPLICATION_X_SV4CPIO = "application/x-sv4cpio";
    public static final String APPLICATION_X_SV4CRC = "application/x-sv4crc";
    public static final String APPLICATION_X_TAR = "application/x-tar";
    public static final String APPLICATION_X_TCL = "application/x-tcl";
    public static final String APPLICATION_X_TEX = "application/x-tex";
    public static final String APPLICATION_X_TEXINFO = "application/x-texinfo";
    public static final String APPLICATION_X_TROFF = "application/x-troff";
    public static final String APPLICATION_X_TROFF_MAN = "application/x-troff-man";
    public static final String APPLICATION_X_TROFF_ME = "application/x-troff-me";
    public static final String APPLICATION_X_TROFF_MS = "application/x-troff-ms";
    public static final String APPLICATION_X_USTAR = "application/x-ustar";
    public static final String APPLICATION_X_WAIS_SOURCE = "application/x-wais-source";
    public static final String APPLICATION_ZIP = "application/zip";
    public static final String AUDIO_BASIC = "audio/basic";
    public static final String AUDIO_MIDI = "audio/midi";
    public static final String AUDIO_MPEG = "audio/mpeg";
    public static final String AUDIO_X_AIFF = "audio/x-aiff";
    public static final String AUDIO_X_MPEGURL = "audio/x-mpegurl";
    public static final String AUDIO_X_PN_REALAUDIO = "audio/x-pn-realaudio";
    public static final String AUDIO_X_WAV = "audio/x-wav";
    public static final String CHEMICAL_X_PDB = "chemical/x-pdb";
    public static final String CHEMICAL_X_XYZ = "chemical/x-xyz";
    public static final String IMAGE_BMP = "image/bmp";
    public static final String IMAGE_CGM = "image/cgm";
    public static final String IMAGE_GIF = "image/gif";
    public static final String IMAGE_IEF = "image/ief";
    public static final String IMAGE_JPEG = "image/jpeg";
    public static final String IMAGE_PNG = "image/png";
    public static final String IMAGE_SVG_XML = "image/svg+xml";
    public static final String IMAGE_TIFF = "image/tiff";
    public static final String IMAGE_VND_DJVU = "image/vnd.djvu";
    public static final String IMAGE_WAP_WBMP = "image/vnd.wap.wbmp";
    public static final String IMAGE_X_CMU_RASTER = "image/x-cmu-raster";
    public static final String IMAGE_X_ICON = "image/x-icon";
    public static final String IMAGE_X_PORTABLE_ANYMAP = "image/x-portable-anymap";
    public static final String IMAGE_X_PORTABLE_BITMAP = "image/x-portable-bitmap";
    public static final String IMAGE_X_PORTABLE_GRAYMAP = "image/x-portable-graymap";
    public static final String IMAGE_X_PORTABLE_PIXMAP = "image/x-portable-pixmap";
    public static final String IMAGE_X_RGB = "image/x-rgb";
    public static final String MODEL_IGES = "model/iges";
    public static final String MODEL_MESH = "model/mesh";
    public static final String MODEL_VRLM = "model/vrml";
    public static final String TEXT_CALENDAR = "text/calendar";
    public static final String TEXT_CSS = "text/css";
    public static final String TEXT_HTML = "text/html";
    public static final String TEXT_PLAIN = "text/plain";
    public static final String TEXT_RICHTEXT = "text/richtext";
    public static final String TEXT_RTF = "text/rtf";
    public static final String TEXT_SGML = "text/sgml";
    public static final String TEXT_TAB_SEPARATED_VALUES = "text/tab-separated-values";
    public static final String TEXT_VND_WAP_WMLSCRIPT = "text/vnd.wap.wmlscript";
    public static final String TEXT_VND_WAP_XML = "text/vnd.wap.wml";
    public static final String TEXT_X_COMPONENT = "text/x-component";
    public static final String TEXT_X_SETEXT = "text/x-setext";
    public static final String VIDEO_MPEG = "video/mpeg";
    public static final String VIDEO_QUICKTIME = "video/quicktime";
    public static final String VIDEO_VND_MPEGURL = "video/vnd.mpegurl";
    public static final String VIDEO_X_MSVIDEO = "video/x-msvideo";
    public static final String VIDEO_X_MS_WMV = "video/x-ms-wmv";
    public static final String VIDEO_X_SGI_MOVIE = "video/x-sgi-movie";
    public static final String X_CONFERENCE_X_COOLTALK = "x-conference/x-cooltalk";
    private static HashMap<String, String> extToType = new HashMap<String, String>() { // from class: com.sony.imaging.app.srctrl.webapi.servlet.MimeType.1
        private static final long serialVersionUID = 1;

        {
            put("xul", MimeType.APPLICATION_VND_MOZZILLA_XUL_XML);
            put("json", "application/json");
            put("ice", MimeType.X_CONFERENCE_X_COOLTALK);
            put("movie", MimeType.VIDEO_X_SGI_MOVIE);
            put("avi", MimeType.VIDEO_X_MSVIDEO);
            put("wmv", MimeType.VIDEO_X_MS_WMV);
            put("m4u", MimeType.VIDEO_VND_MPEGURL);
            put("mxu", MimeType.VIDEO_VND_MPEGURL);
            put("htc", MimeType.TEXT_X_COMPONENT);
            put("etx", MimeType.TEXT_X_SETEXT);
            put("wmls", MimeType.TEXT_VND_WAP_WMLSCRIPT);
            put("wml", MimeType.TEXT_VND_WAP_XML);
            put("tsv", MimeType.TEXT_TAB_SEPARATED_VALUES);
            put("sgm", MimeType.TEXT_SGML);
            put("sgml", MimeType.TEXT_SGML);
            put("css", MimeType.TEXT_CSS);
            put("ifb", MimeType.TEXT_CALENDAR);
            put("ics", MimeType.TEXT_CALENDAR);
            put("wrl", MimeType.MODEL_VRLM);
            put("vrlm", MimeType.MODEL_VRLM);
            put("silo", MimeType.MODEL_MESH);
            put("mesh", MimeType.MODEL_MESH);
            put("msh", MimeType.MODEL_MESH);
            put("iges", MimeType.MODEL_IGES);
            put("igs", MimeType.MODEL_IGES);
            put("rgb", MimeType.IMAGE_X_RGB);
            put("ppm", MimeType.IMAGE_X_PORTABLE_PIXMAP);
            put("pgm", MimeType.IMAGE_X_PORTABLE_GRAYMAP);
            put("pbm", MimeType.IMAGE_X_PORTABLE_BITMAP);
            put("pnm", MimeType.IMAGE_X_PORTABLE_ANYMAP);
            put("ico", MimeType.IMAGE_X_ICON);
            put("ras", MimeType.IMAGE_X_CMU_RASTER);
            put("wbmp", MimeType.IMAGE_WAP_WBMP);
            put("djv", MimeType.IMAGE_VND_DJVU);
            put("djvu", MimeType.IMAGE_VND_DJVU);
            put("svg", MimeType.IMAGE_SVG_XML);
            put("ief", MimeType.IMAGE_IEF);
            put("cgm", MimeType.IMAGE_CGM);
            put("bmp", MimeType.IMAGE_BMP);
            put("xyz", MimeType.CHEMICAL_X_XYZ);
            put("pdb", MimeType.CHEMICAL_X_PDB);
            put("ra", MimeType.AUDIO_X_PN_REALAUDIO);
            put("ram", MimeType.AUDIO_X_PN_REALAUDIO);
            put("m3u", MimeType.AUDIO_X_MPEGURL);
            put("aifc", MimeType.AUDIO_X_AIFF);
            put("aif", MimeType.AUDIO_X_AIFF);
            put("aiff", MimeType.AUDIO_X_AIFF);
            put("mp3", MimeType.AUDIO_MPEG);
            put("mp2", MimeType.AUDIO_MPEG);
            put("mp1", MimeType.AUDIO_MPEG);
            put("mpga", MimeType.AUDIO_MPEG);
            put("kar", MimeType.AUDIO_MIDI);
            put("mid", MimeType.AUDIO_MIDI);
            put("midi", MimeType.AUDIO_MIDI);
            put("dtd", MimeType.APPLICATION_XML_DTD);
            put("xsl", MimeType.APPLICATION_XML);
            put("xml", MimeType.APPLICATION_XML);
            put("xslt", MimeType.APPLICATION_XSLT_XML);
            put("xht", MimeType.APPLICATION_XHTML_XML);
            put("xhtml", MimeType.APPLICATION_XHTML_XML);
            put("src", MimeType.APPLICATION_X_WAIS_SOURCE);
            put("ustar", MimeType.APPLICATION_X_USTAR);
            put("ms", MimeType.APPLICATION_X_TROFF_MS);
            put("me", MimeType.APPLICATION_X_TROFF_ME);
            put("man", MimeType.APPLICATION_X_TROFF_MAN);
            put("roff", MimeType.APPLICATION_X_TROFF);
            put("tr", MimeType.APPLICATION_X_TROFF);
            put("t", MimeType.APPLICATION_X_TROFF);
            put("texi", MimeType.APPLICATION_X_TEXINFO);
            put("texinfo", MimeType.APPLICATION_X_TEXINFO);
            put("tex", MimeType.APPLICATION_X_TEX);
            put("tcl", MimeType.APPLICATION_X_TCL);
            put("sv4crc", MimeType.APPLICATION_X_SV4CRC);
            put("sv4cpio", MimeType.APPLICATION_X_SV4CPIO);
            put("sit", MimeType.APPLICATION_X_STUFFIT);
            put("swf", MimeType.APPLICATION_X_SHOCKWAVE_FLASH);
            put("shar", MimeType.APPLICATION_X_SHAR);
            put("sh", MimeType.APPLICATION_X_SH);
            put("cdf", MimeType.APPLICATION_X_NETCDF);
            put("nc", MimeType.APPLICATION_X_NETCDF);
            put("latex", MimeType.APPLICATION_X_LATEX);
            put("skm", MimeType.APPLICATION_X_KOAN);
            put("skt", MimeType.APPLICATION_X_KOAN);
            put("skd", MimeType.APPLICATION_X_KOAN);
            put("skp", MimeType.APPLICATION_X_KOAN);
            put("js", MimeType.APPLICATION_X_JAVASCRIPT);
            put("hdf", MimeType.APPLICATION_X_HDF);
            put("gtar", MimeType.APPLICATION_X_GTAR);
            put("spl", MimeType.APPLICATION_X_FUTURESPLASH);
            put("dvi", MimeType.APPLICATION_X_DVI);
            put("dxr", MimeType.APPLICATION_X_DIRECTOR);
            put("dir", MimeType.APPLICATION_X_DIRECTOR);
            put("dcr", MimeType.APPLICATION_X_DIRECTOR);
            put("csh", MimeType.APPLICATION_X_CSH);
            put("cpio", MimeType.APPLICATION_X_CPIO);
            put("pgn", MimeType.APPLICATION_X_CHESS_PGN);
            put("vcd", MimeType.APPLICATION_X_CDLINK);
            put("bcpio", MimeType.APPLICATION_X_BCPIO);
            put("rm", MimeType.APPLICATION_VND_RNREALMEDIA);
            put("ppt", MimeType.APPLICATION_VND_MSPOWERPOINT);
            put("mif", MimeType.APPLICATION_VND_MIF);
            put("grxml", MimeType.APPLICATION_SRGS_XML);
            put("gram", MimeType.APPLICATION_SRGS);
            put("smil", MimeType.APPLICATION_RDF_SMIL);
            put("smi", MimeType.APPLICATION_RDF_SMIL);
            put("rdf", MimeType.APPLICATION_RDF_XML);
            put("ogg", MimeType.APPLICATION_X_OGG);
            put("oda", MimeType.APPLICATION_ODA);
            put("dmg", "application/octet-stream");
            put("lzh", "application/octet-stream");
            put("so", "application/octet-stream");
            put("lha", "application/octet-stream");
            put("dms", "application/octet-stream");
            put("bin", "application/octet-stream");
            put("mathml", MimeType.APPLICATION_MATHML_XML);
            put("cpt", MimeType.APPLICATION_MAC_COMPACTPRO);
            put("hqx", MimeType.APPLICATION_MAC_BINHEX40);
            put("jnlp", MimeType.APPLICATION_JNLP);
            put("ez", MimeType.APPLICATION_ANDREW_INSET);
            put("txt", MimeType.TEXT_PLAIN);
            put("ini", MimeType.TEXT_PLAIN);
            put("c", MimeType.TEXT_PLAIN);
            put("h", MimeType.TEXT_PLAIN);
            put("cpp", MimeType.TEXT_PLAIN);
            put("cxx", MimeType.TEXT_PLAIN);
            put("cc", MimeType.TEXT_PLAIN);
            put("chh", MimeType.TEXT_PLAIN);
            put("java", MimeType.TEXT_PLAIN);
            put("csv", MimeType.TEXT_PLAIN);
            put("bat", MimeType.TEXT_PLAIN);
            put("cmd", MimeType.TEXT_PLAIN);
            put("asc", MimeType.TEXT_PLAIN);
            put("rtf", MimeType.TEXT_RTF);
            put("rtx", MimeType.TEXT_RICHTEXT);
            put(SRCtrlConstants.FILE_EXTENTION_HTML, MimeType.TEXT_HTML);
            put("htm", MimeType.TEXT_HTML);
            put("zip", MimeType.APPLICATION_ZIP);
            put("rar", MimeType.APPLICATION_X_RAR_COMPRESSED);
            put("gzip", MimeType.APPLICATION_X_GZIP);
            put("gz", MimeType.APPLICATION_X_GZIP);
            put("tgz", MimeType.APPLICATION_TGZ);
            put("tar", MimeType.APPLICATION_X_TAR);
            put("gif", MimeType.IMAGE_GIF);
            put("jpeg", MimeType.IMAGE_JPEG);
            put("jpg", MimeType.IMAGE_JPEG);
            put("jpe", MimeType.IMAGE_JPEG);
            put("tiff", MimeType.IMAGE_TIFF);
            put("tif", MimeType.IMAGE_TIFF);
            put("png", MimeType.IMAGE_PNG);
            put("au", MimeType.AUDIO_BASIC);
            put("snd", MimeType.AUDIO_BASIC);
            put("wav", MimeType.AUDIO_X_WAV);
            put("mov", MimeType.VIDEO_QUICKTIME);
            put("qt", MimeType.VIDEO_QUICKTIME);
            put("mpeg", MimeType.VIDEO_MPEG);
            put("mpg", MimeType.VIDEO_MPEG);
            put("mpe", MimeType.VIDEO_MPEG);
            put("abs", MimeType.VIDEO_MPEG);
            put("doc", MimeType.APPLICATION_MSWORD);
            put("xls", MimeType.APPLICATION_VND_MSEXCEL);
            put("eps", MimeType.APPLICATION_POSTSCRIPT);
            put("ai", MimeType.APPLICATION_POSTSCRIPT);
            put("ps", MimeType.APPLICATION_POSTSCRIPT);
            put("pdf", MimeType.APPLICATION_PDF);
            put("exe", "application/octet-stream");
            put("dll", "application/octet-stream");
            put("class", "application/octet-stream");
            put("jar", MimeType.APPLICATION_JAVA_ARCHIVE);
        }
    };

    private MimeType() {
    }

    public static String getType(String ext) {
        String mimeType = extToType.get(ext.toLowerCase());
        if (mimeType == null) {
            return "application/octet-stream";
        }
        return mimeType;
    }

    public static void putType(String ext, String mimeType) {
        extToType.put(ext, mimeType);
    }
}
