package com.sony.imaging.app.manuallenscompensation.commonUtil;

/* loaded from: classes.dex */
public class OCBackUpKey {
    public static final String KEY_BKUP_COUNT_DELETE_EXPORTED_LIST = "KEY_BKUP_COUNT_DELETE_EXPORTED_LIST";
    public static final String KEY_BKUP_COUNT_IMPORT_EXPORTED_LIST = "KEY_BKUP_COUNT_IMPORT_EXPORTED_LIST";
    public static final String KEY_BKUP_LAST_MEDIASTATE_FOR_START = "KEY_BKUP_LAST_MEDIASTATE_FOR_START";
    public static final String KEY_BKUP_PREV_RECORD_ID = "KEY_BKUP_PREV_RECORD_ID";
    public static final String KEY_BKUP_SELECTED_PARAM = "KEY_BKUP_SELECTED_PARAM";
    public static final String KEY_BKUP_SELECTED_POSITION = "KEY_BKUP_SELECTED_POSITION";
    public static final String KEY_BKUP_SELECTED_SPARS_ARRAY_LIST = "KEY_BKUP_SELECTED_SPARS_ARRAY_LIST";
    public static String KEY_BKUP_GRIDLINE_STATE = "KEY_BKUP_GRIDLINE_STATE";
    public static String KEY_DIADEM_EXPOSURE_MODE = "KEY_DIADEM_EXPOSURE_MODE";
    public static String KEY_DIADEM_DRIVE_MODE = "KEY_DIADEM_DRIVE_MODE";
    public static String KEY_BKUP_SELECTED_POSITION_DELETE_EXPORTED_LIST = "KEY_BKUP_SELECTED_POSITION_DELETE_EXPORTED_LIST";
    public static String KEY_BKUP_SELECTED_POSITION_IMPORT_EXPORTED_LIST = "KEY_BKUP_SELECTED_POSITION_IMPORT_EXPORTED_LIST";
}
