package com.sony.imaging.app.manuallenscompensation.commonUtil;

import com.sony.imaging.app.manuallenscompensation.R;
import com.sony.imaging.app.manuallenscompensation.shooting.controller.OCController;
import java.util.ArrayList;
import java.util.List;

/* loaded from: classes.dex */
public class OCConstants {
    public static final String APP_VERSION = "01.00";
    public static final String BLANCK_SPACE_STRING = " ";
    public static final String BLANK_FVALUE_STR = " . ";
    public static final String BLANK_PROFILE_LENS_NAME_STR = "--";
    public static final String BLANK_SPACE_STR = " ";
    public static final String DB_PATH_EXTENSION = ".txt";
    public static final String DB_VERSION = "01.00";
    public static final String DECIMAL_ZERO = "0.0";
    public static final int DIGIT_EIGHT = 8;
    public static final int DIGIT_FIVE = 5;
    public static final int DIGIT_FOUR = 4;
    public static final int DIGIT_MAX_F_VALUE = 99;
    public static final int DIGIT_MAX_PARAMETER_VALUE = 16;
    public static final int DIGIT_MIN_PARAMETER_VALUE = -16;
    public static final int DIGIT_NINE = 9;
    public static final int DIGIT_ONE = 1;
    public static final int DIGIT_SEVEN = 7;
    public static final int DIGIT_SIX = 6;
    public static final int DIGIT_THREE = 3;
    public static final int DIGIT_TWO = 2;
    public static final int DIGIT_ZERO = 0;
    public static final String DOT_STRING = ".";
    public static final double DOUBLE_ZERO = 0.0d;
    public static final String EE_STATE = "EE";
    public static final String EMPTY_STRING = "";
    public static final String EMPTY_STRING_FVALUE = "F--";
    public static final String EXPOSURE_MODE_STATE = "ExposureModeCheck";
    public static final String EXTERNAL_PROFILE_FILE_NAME = "External_File_Name";
    public static final String FILE_EXTENTION = ".BIN";
    public static final String FILE_PREFIX = "LENS0";
    public static final String FOCALLENGTH_NULL_STRING = "0mm";
    public static final String FOCALLENGTH_UNIT_STRING = "mm";
    public static final String FORMAT = "%03d";
    public static final int FOUR_NINETY_SIX = 496;
    public static final String F_VAL_PREFIX_STRING = "F";
    public static final String ID_DELETEPROFILECONFIRM = "ID_DELETESINGLECONFIRMMENULAYOUT";
    public static final String ID_DELETEPROFILEPROCESSING = "ID_DELETEPROFILEPROCESSINGMENULAYOUT";
    public static final String ID_PAGEMENULAYOUT = "ID_PAGEMENULAYOUT";
    public static final int INVALID_POSITION = -1;
    public static final String LENS_NAME_NULL_STRING = "--";
    public static final int LEVEL_GAUGE_BALANCING_NUMBER = 16;
    public static final long LONG_EIGHTY = 80;
    public static final long LONG_TWOHUNDRED = 200;
    public static final int MAX_EXTERNAL_PROFILE_COUNT = 200;
    public static final int MAX_PROFILE_COUNT = 100;
    public static final String MENU_KIND = "AppTop";
    public static final String MENU_SETTING_KIND = "ApplicationSettings";
    public static final String MENU_SETTING_KIND_ADJUST = "AdjustMenu";
    public static final String MENU_SETTING_KIND_Delete = "DeleteMenu";
    public static final String MENU_SETTING_KIND_EDIT = "EditMenu";
    public static final String MENU_STATE = "Menu";
    public static final String MENU_TAG = "ItemId";
    public static final String MS_CARD_PATH = "/MSSONY/CAM_APPS/APP_LC/PROFILE";
    public static final String NEXT_STATE = "EE";
    public static final short NEXT_VER_OFFSET = 490;
    public static final String OC_S1OFF_EE_STATE = "OCS1OFFEEState";
    public static final String OC_S1OFF_EE_STATE_KEYHANDLER = "OCS1OFFEEStateKeyHandler";
    public static final String OC_S1ON_EE_STATE = "OCS1OnEEState";
    public static final String PROFILE_ACTION = "PROFILE_ACTION";
    public static final int PROFILE_ACTION_DELETE = 0;
    public static final int PROFILE_ACTION_EXPORT = 1;
    public static final int PROFILE_ACTION_EXTERNAL_PROFILE_DELETE = 3;
    public static final int PROFILE_ACTION_IMPORT = 2;
    public static final int PROFILE_PROCESS_DELETE_ERROR = 0;
    public static final String PROFILE_PROCESS_ERROR = "PROFILE_PROCESS_ERROR";
    public static final int PROFILE_PROCESS_EXPORT_ERROR = 1;
    public static final int PROFILE_PROCESS_IMPORT_ERROR = 2;
    public static final int SCREEN_EXTERNAL = 1;
    public static final int SCREEN_INTERNAL = 0;
    public static final String SD_CARD_PATH = "/PRIVATE/SONY/APP_LC/PROFILE";
    public static List<String> SETTINGSSUPPORTED = null;
    public static final int SETTING_COLOR = 3;
    public static final int SETTING_DISTORTION = 5;
    public static final int SETTING_FVALUE = 12;
    public static final int SETTING_FVALUE_ONE = 13;
    public static final int SETTING_FVALUE_SECOND = 14;
    public static final String SETTING_KIND = "ID_LENS_CORRECTION_COMPENSATION_SETTING_KIND";
    public static final int SETTING_LIGHT = 0;
    public static final int SETTING_NAME = 11;
    public static final int SETTING_SAVE = 10;
    public static final String SORT_ORDER = "_id ASC";
    public static final String STRING_ERROR = "ERROR";
    public static final String TAG_DB_UPDATE_PROCESS = "extdbsynchfinish";
    public static final String TAG_DELETE_PROCESS = "TAG_DELETE_PROCESS";
    public static final String TAG_DELETE_PROCESS_CANCEL = "TAG_DELETE_PROCESS_CANCEL";
    public static final int TIME_GUIDE = 2000;
    public static final String TYPE_INFO_DB_PATH = "/PRIVATE/";
    public static final String TYPE_INFO_FILENAME = "TYPEINFO.XML";
    public static final int VALID_FILE_NAME_LENGTH = 12;
    public static final String ZERO_FVALUE_STR = "0";
    public static int profileAction = 0;
    public static int THREE_NINETY_TWO = 392;
    public static int THREE_NINETY_THREE = 393;
    public static int THREE_NINETY_FOUR = 394;
    public static int THREE_NINETY_FIVE = 395;
    public static int THREE_NINETY_SIX = 396;
    public static int THREE_NINETY_SEVEN = 397;
    public static int THREE_NINETY_EIGHT = 398;
    public static int THREE_NINETY_NINE = 399;
    public static int FOUR_HUNDRED = 400;
    public static int FOUR_HUNDRED_ONE = 401;
    public static int FOUR_HUNDRED_TWO = 402;
    public static int FOUR_HUNDRED_THREE = 403;
    public static int FOUR_HUNDRED_FOUR = 404;
    public static int FOUR_HUNDRED_FIVE = 405;
    public static int FOUR_HUNDRED_SIX = 406;
    public static int FOUR_HUNDRED_SEVEN = 407;
    public static int FOUR_HUNDRED_EIGHT = 408;
    public static int FOUR_HUNDRED_NINE = 409;
    public static int FOUR_HUNDRED_TEN = 410;
    public static String EVSTEP_ZERO_TO_THREE = "0-3EV";
    public static String EVSTEP_ZERO_TO_FIVE = "0-5EV";
    public static String EVSTEP_ONE_TO_ZERO = "1-0EV";
    public static final String ACTION_SELECTED_EDIT = AppContext.getAppContext().getResources().getString(R.string.STRID_FUNC_AP_EDIT_BTN);
    public static final String ACTION_SELECTED_NEW = AppContext.getAppContext().getResources().getString(R.string.STRID_FUNC_OPTICAL_COMPENSATION_PROFILE_CREATE);
    public static String TAG_IMPORT_SUCCESSFUL = "TAG_IMPORT_SUCCESSFUL";
    public static final Short MAX_NAME_LENGTH = 384;
    public static final Short DIGIT_MAX_F_LENGTH_VALUE = 9999;

    static {
        if (SETTINGSSUPPORTED == null) {
            SETTINGSSUPPORTED = new ArrayList();
        }
        SETTINGSSUPPORTED.add(OCController.LIGHT_VIGNETTING);
        SETTINGSSUPPORTED.add(OCController.RED_COLOR_VIGNETTING);
        SETTINGSSUPPORTED.add(OCController.BLUE_COLOR_VIGNETTING);
        SETTINGSSUPPORTED.add(OCController.RED_CHROMATIC_ABERRATION);
        SETTINGSSUPPORTED.add(OCController.BLUE_CHROMATIC_ABERRATION);
        SETTINGSSUPPORTED.add(OCController.DISTORTION);
    }
}
